name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: # allows manual triggering of the workflow

env:
  TEST_TAG: ghcr.io/tobias38/simple-node-app:test
  LATEST_TAG: ghcr.io/tobias38/simple-node-app:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test
        run: |
          docker run -d --rm -p 3000:3000 ${{ env.TEST_TAG }}
          sleep 5s
          curl http://localhost:3000

      - name: Push to registry
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}