name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: # allows manual triggering of the workflow

env:
  BUILD_VERSION: 1.0.${{ github.run_number }}
  DOCKER_TAG_BASE: ghcr.io/tobias38/simple-node-app
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CONTAINER_REGISTRY_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ${{ env.DOCKER_TAG_BASE }}:latest

      - name: Test
        run: |
          docker run -d --rm -p 3000:3000 ${{ env.DOCKER_TAG_BASE }}:latest
          curl --retry 10 -f --retry-all-errors --retry-delay 5 http://localhost:3000

      - name: Push to registry
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_TAG_BASE }}:latest ${{ env.DOCKER_TAG_BASE }}:${{ env.BUILD_VERSION }}

      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a "v${{ env.BUILD_VERSION }}" -m "Release v${{ env.BUILD_VERSION }}"
          git push origin "v${{ env.BUILD_VERSION }}"