name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: ghcr.io/tobias38/simple-node-app:latest
